FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
CMD [ "npm", "start" ]

# RUN
# image build

# CMD/ENTRYPOINT
# run container

# CMD
# can override

# ENTRYPOINT
# can not override
