version: '3'

# create network and isolate containers from the others.
# https://docs.docker.jp/compose/compose-file/index.html#id43
# https://knowledge.sakura.ad.jp/26522/
networks: 
  react_express:
    driver: bridge

services:
  frontend: # servise name
    build: ./frontend # path Dockerfile
    container_name: front # container name
    tty: true # It is needed for keeping on running container.
    ports: # port
      - 3001:3000
    networks: # atattched network 
      - react_express
  backend:
    build: ./backend
    container_name: back
    tty: true
    ports:
      - 3002:3000
    networks:
      - react_express
