version: '3'

networks:
  react_express:
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: front
    tty: true
    ports:
      - 3001:3000
    networks:
      - react_express
  backend:
    build: ./backend
    container_name: back
    tty: true
    ports:
      - 3002:3000
    networks:
      - react_express
